### ISSUE TITLE
SA1650 No errors and CustomDictionary.xml

### ISSUE THREAD

**Issue by SonizciTR** [rfennell/StyleCopCmdLine#5]
When your "Settings.StyleCop" file only active rule is SA1650, nothing fails. 
I followed these steps:
Unchecked all other rules, checked only SA1650 and save. Before run "StyleCop Runner by Black Marble" build step, double checked that it is looking right setting file. Finally run. At the end of the run it is not failing. At output window, I see : "No violations found"
But when i open the solution from Agent Folder and run stylecop it sees a lot of SA1650 warnings.

My main goal was, code is adding CustomDictionary.xml that you use. If you have CustomDictionary.xml file, you can add a lot of Acronyms. Code should ignore SA1650 warnings that word matches at CustomDictionary.xml's Acronyms part.

P.S.: At this link [this](http://stackoverflow.com/questions/12682642/specify-path-to-customdictionary-file-for-stylecop-spellchecking) they are advacing to put  CustomDictionary.xml file's folder to Spelling part of "Settings.StyleCop" . But it is more flexible if we can add CustomDictionary.xml file or path at the code. This will give more flexibility.

**Comment by rfennell** [comment]
Wow that took a while to track down. 

The issue is actually a simple one in the end, for any rules that are dictionary based the mssp7en.dll and mssp7en.lex files need to be copied to the same folder as the StyleCop.dll (exactly the same for the rules assemblies) 

I have written a unit test to exercise the SA1650 rule, for it work note that a post build event is run to place the files in the correct locations.

You issue hints you are trying to run this rule within my VSTS StyleCop task, so need to make similar changes for that extension. The extension should include the dictionary files

**Comment by SonizciTR** [comment]
Thanks it worked

**Comment by SonizciTR** [comment]
Sorry, i runned code at debug it is working. Jump the guns problem solved.

I deleted the old task. Uploeded the task that you already added "mssp7en.*" files. When I runed the task at TFS, it writes "No violations found". Task not working at TFS for SA 1650. :(

**Comment by rfennell** [comment]
Seems to be some confusion here, I have only solved the problem in the StyleCopCommandLine EXE code i.e this [git repo](https://github.com/rfennell/StyleCopCmdLine)

I am still looking at the code in the [vNextBuild extensions repo ](https://github.com/rfennell/vnextbuild) where the VSTS Extensions are kept. I have not yet published a version of the Extension that runs SA1650 errors. I did commit code last night, but it does not work yet. I am planning to re-architect the task to allow me to introduce Pester based tests.

Not sure when I will have time to do this, or keep an you out for a published extension in the VSTS marketplace

**Comment by rfennell** [comment]
Fixed in 1.6.15 of the StyleCop Task extension
The problem is that though many rules in StyleCop run in both 32 and 64 bit environments this is not the case for any that use a dictionary. These only work in 32bit mode, hence we have to jump thotuhg some hoops to make the call to the StyleCopCmdLine is done in a 32bit instance of PowerShell.
